using System.Collections.Generic;
using System.Threading.Tasks;
using SQLite;
using SQLiteDB.Resources.Model;

namespace Database
{
    public class SoundDatabase
    {
        private readonly SQLiteAsyncConnection _database;

        public SoundDatabase(string dbPath)
        {
            _database = new SQLiteAsyncConnection(dbPath);
            _database.CreateTableAsync<SoundProps>();
            _database.CreateTableAsync<Tuning>();
            _database.CreateTableAsync<Scales>();
        }

        //===========================================

        public Task<int> InsertAllNotes(int notesCount)
        {

            //Id. MinFreq. Freq. MaxFreq. Note
            List<SoundProps> notes = new List<SoundProps>
            {
               new SoundProps { Id =1, MinFreq = 0, Frequency = 16.35, MaxFreq = 16.835, Note = "C0"},
                new SoundProps { Id =2, MinFreq = 16.845, Frequency = 17.32, MaxFreq = 17.835, Note = "C#0"},
                new SoundProps { Id =3, MinFreq = 17.845, Frequency = 18.35, MaxFreq = 18.9, Note = "D0"},
                new SoundProps { Id =4, MinFreq = 18.91, Frequency = 19.45, MaxFreq = 20.025, Note = "D#0"},
                new SoundProps { Id =5, MinFreq = 20.035, Frequency = 20.6, MaxFreq = 21.215, Note = "E0"},
                new SoundProps { Id =6, MinFreq = 21.225, Frequency = 21.83, MaxFreq = 22.475, Note = "F0"},
                new SoundProps { Id =7, MinFreq = 22.485, Frequency = 23.12, MaxFreq = 23.81, Note = "F#0"},
                new SoundProps { Id =8, MinFreq = 23.82, Frequency = 24.5, MaxFreq = 25.23, Note = "G0"},
                new SoundProps { Id =9, MinFreq = 25.24, Frequency = 25.96, MaxFreq = 26.73, Note = "G#0"},
                new SoundProps { Id =10, MinFreq = 26.74, Frequency = 27.5, MaxFreq = 28.32, Note = "A0"},
                new SoundProps { Id =11, MinFreq = 28.33, Frequency = 29.14, MaxFreq = 30.005, Note = "A#0"},
                new SoundProps { Id =12, MinFreq = 30.015, Frequency = 30.87, MaxFreq = 31.785, Note = "B0"},
                new SoundProps { Id =13, MinFreq = 31.795, Frequency = 32.7, MaxFreq = 33.675, Note = "C1"},
                new SoundProps { Id =14, MinFreq = 33.685, Frequency = 34.65, MaxFreq = 35.68, Note = "C#1"},
                new SoundProps { Id =15, MinFreq = 35.69, Frequency = 36.71, MaxFreq = 37.8, Note = "D1"},
                new SoundProps { Id =16, MinFreq = 37.81, Frequency = 38.89, MaxFreq = 40.045, Note = "D#1"},
                new SoundProps { Id =17, MinFreq = 40.055, Frequency = 41.2, MaxFreq = 42.425, Note = "E1"},
                new SoundProps { Id =18, MinFreq = 42.435, Frequency = 43.65, MaxFreq = 44.95, Note = "F1"},
                new SoundProps { Id =19, MinFreq = 44.96, Frequency = 46.25, MaxFreq = 47.625, Note = "F#1"},
                new SoundProps { Id =20, MinFreq = 47.635, Frequency = 49, MaxFreq = 50.455, Note = "G1"},
                new SoundProps { Id =21, MinFreq = 50.465, Frequency = 51.91, MaxFreq = 53.455, Note = "G#1"},
                new SoundProps { Id =22, MinFreq = 53.465, Frequency = 55, MaxFreq = 56.635, Note = "A1"},
                new SoundProps { Id =23, MinFreq = 56.645, Frequency = 58.27, MaxFreq = 60.005, Note = "A#1"},
                new SoundProps { Id =24, MinFreq = 60.015, Frequency = 61.74, MaxFreq = 63.575, Note = "B1"},
                new SoundProps { Id =25, MinFreq = 63.585, Frequency = 65.41, MaxFreq = 67.355, Note = "C2"},
                new SoundProps { Id =26, MinFreq = 67.365, Frequency = 69.3, MaxFreq = 71.36, Note = "C#2"},
                new SoundProps { Id =27, MinFreq = 71.37, Frequency = 73.42, MaxFreq = 75.6, Note = "D2"},
                new SoundProps { Id =28, MinFreq = 75.61, Frequency = 77.78, MaxFreq = 80.095, Note = "D#2"},
                new SoundProps { Id =29, MinFreq = 80.105, Frequency = 82.41, MaxFreq = 84.86, Note = "E2"},
                new SoundProps { Id =30, MinFreq = 84.87, Frequency = 87.31, MaxFreq = 89.905, Note = "F2"},
                new SoundProps { Id =31, MinFreq = 89.915, Frequency = 92.5, MaxFreq = 95.25, Note = "F#2"},
                new SoundProps { Id =32, MinFreq = 95.26, Frequency = 98, MaxFreq = 100.915, Note = "G2"},
                new SoundProps { Id =33, MinFreq = 100.925, Frequency = 103.83, MaxFreq = 106.915, Note = "G#2"},
                new SoundProps { Id =34, MinFreq = 106.925, Frequency = 110, MaxFreq = 113.27, Note = "A2"},
                new SoundProps { Id =35, MinFreq = 113.28, Frequency = 116.54, MaxFreq = 120.005, Note = "A#2"},
                new SoundProps { Id =36, MinFreq = 120.015, Frequency = 123.47, MaxFreq = 127.14, Note = "B2"},
                new SoundProps { Id =37, MinFreq = 127.15, Frequency = 130.81, MaxFreq = 134.7, Note = "C3"},
                new SoundProps { Id =38, MinFreq = 134.71, Frequency = 138.59, MaxFreq = 142.71, Note = "C#3"},
                new SoundProps { Id =39, MinFreq = 142.72, Frequency = 146.83, MaxFreq = 151.195, Note = "D3"},
                new SoundProps { Id =40, MinFreq = 151.205, Frequency = 155.56, MaxFreq = 160.185, Note = "D#3"},
                new SoundProps { Id =41, MinFreq = 160.195, Frequency = 164.81, MaxFreq = 169.71, Note = "E3"},
                new SoundProps { Id =42, MinFreq = 169.72, Frequency = 174.61, MaxFreq = 179.805, Note = "F3"},
                new SoundProps { Id =43, MinFreq = 179.815, Frequency = 185, MaxFreq = 190.5, Note = "F#3"},
                new SoundProps { Id =44, MinFreq = 190.51, Frequency = 196, MaxFreq = 201.825, Note = "G3"},
                new SoundProps { Id =45, MinFreq = 201.835, Frequency = 207.65, MaxFreq = 213.825, Note = "G#3"},
                new SoundProps { Id =46, MinFreq = 213.835, Frequency = 220, MaxFreq = 226.54, Note = "A3"},
                new SoundProps { Id =47, MinFreq = 226.55, Frequency = 233.08, MaxFreq = 240.01, Note = "A#3"},
                new SoundProps { Id =48, MinFreq = 240.02, Frequency = 246.94, MaxFreq = 254.285, Note = "B3"},
                new SoundProps { Id =49, MinFreq = 254.295, Frequency = 261.63, MaxFreq = 269.405, Note = "C4"},
                new SoundProps { Id =50, MinFreq = 269.415, Frequency = 277.18, MaxFreq = 285.42, Note = "C#4"},
                new SoundProps { Id =51, MinFreq = 285.43, Frequency = 293.66, MaxFreq = 302.395, Note = "D4"},
                new SoundProps { Id =52, MinFreq = 302.405, Frequency = 311.13, MaxFreq = 320.38, Note = "D#4"},
                new SoundProps { Id =53, MinFreq = 320.39, Frequency = 329.63, MaxFreq = 339.43, Note = "E4"},
                new SoundProps { Id =54, MinFreq = 339.44, Frequency = 349.23, MaxFreq = 359.61, Note = "F4"},
                new SoundProps { Id =55, MinFreq = 359.62, Frequency = 369.99, MaxFreq = 380.995, Note = "F#4"},
                new SoundProps { Id =56, MinFreq = 381.005, Frequency = 392, MaxFreq = 403.65, Note = "G4"},
                new SoundProps { Id =57, MinFreq = 403.66, Frequency = 415.3, MaxFreq = 427.65, Note = "G#4"},
                new SoundProps { Id =58, MinFreq = 427.66, Frequency = 440, MaxFreq = 453.08, Note = "A4"},
                new SoundProps { Id =59, MinFreq = 453.09, Frequency = 466.16, MaxFreq = 480.02, Note = "A#4"},
                new SoundProps { Id =60, MinFreq = 480.03, Frequency = 493.88, MaxFreq = 508.565, Note = "B4"},
                new SoundProps { Id =61, MinFreq = 508.575, Frequency = 523.25, MaxFreq = 538.81, Note = "C5"},
                new SoundProps { Id =62, MinFreq = 538.82, Frequency = 554.37, MaxFreq = 570.85, Note = "C#5"},
                new SoundProps { Id =63, MinFreq = 570.86, Frequency = 587.33, MaxFreq = 604.79, Note = "D5"},
                new SoundProps { Id =64, MinFreq = 604.8, Frequency = 622.25, MaxFreq = 640.75, Note = "D#5"},
                new SoundProps { Id =65, MinFreq = 640.76, Frequency = 659.25, MaxFreq = 678.855, Note = "E5"},
                new SoundProps { Id =66, MinFreq = 678.865, Frequency = 698.46, MaxFreq = 719.225, Note = "F5"},
                new SoundProps { Id =67, MinFreq = 719.235, Frequency = 739.99, MaxFreq = 761.99, Note = "F#5"},
                new SoundProps { Id =68, MinFreq = 762, Frequency = 783.99, MaxFreq = 807.3, Note = "G5"},
                new SoundProps { Id =69, MinFreq = 807.31, Frequency = 830.61, MaxFreq = 855.305, Note = "G#5"},
                new SoundProps { Id =70, MinFreq = 855.315, Frequency = 880, MaxFreq = 906.165, Note = "A5"},
                new SoundProps { Id =71, MinFreq = 906.175, Frequency = 932.33, MaxFreq = 960.05, Note = "A#5"},
                new SoundProps { Id =72, MinFreq = 960.06, Frequency = 987.77, MaxFreq = 1017.135, Note = "B5"},
                new SoundProps { Id =73, MinFreq = 1017.145, Frequency = 1046.5, MaxFreq = 1077.615, Note = "C6"},
                new SoundProps { Id =74, MinFreq = 1077.625, Frequency = 1108.73, MaxFreq = 1141.695, Note = "C#6"},
                new SoundProps { Id =75, MinFreq = 1141.705, Frequency = 1174.66, MaxFreq = 1209.585, Note = "D6"},
                new SoundProps { Id =76, MinFreq = 1209.595, Frequency = 1244.51, MaxFreq = 1281.51, Note = "D#6"},
                new SoundProps { Id =77, MinFreq = 1281.52, Frequency = 1318.51, MaxFreq = 1357.71, Note = "E6"},
                new SoundProps { Id =78, MinFreq = 1357.72, Frequency = 1396.91, MaxFreq = 1438.445, Note = "F6"},
                new SoundProps { Id =79, MinFreq = 1438.455, Frequency = 1479.98, MaxFreq = 1523.98, Note = "F#6"},
                new SoundProps { Id =80, MinFreq = 1523.99, Frequency = 1567.98, MaxFreq = 1614.6, Note = "G6"},
                new SoundProps { Id =81, MinFreq = 1614.61, Frequency = 1661.22, MaxFreq = 1710.61, Note = "G#6"},
                new SoundProps { Id =82, MinFreq = 1710.62, Frequency = 1760, MaxFreq = 1812.33, Note = "A6"},
                new SoundProps { Id =83, MinFreq = 1812.34, Frequency = 1864.66, MaxFreq = 1920.095, Note = "A#6"},
                new SoundProps { Id =84, MinFreq = 1920.105, Frequency = 1975.53, MaxFreq = 2034.265, Note = "B6"},
                new SoundProps { Id =85, MinFreq = 2034.275, Frequency = 2093, MaxFreq = 2155.23, Note = "C7"},
                new SoundProps { Id =86, MinFreq = 2155.24, Frequency = 2217.46, MaxFreq = 2283.39, Note = "C#7"},
                new SoundProps { Id =87, MinFreq = 2283.4, Frequency = 2349.32, MaxFreq = 2419.17, Note = "D7"},
                new SoundProps { Id =88, MinFreq = 2419.18, Frequency = 2489.02, MaxFreq = 2563.02, Note = "D#7"},
                new SoundProps { Id =89, MinFreq = 2563.03, Frequency = 2637.02, MaxFreq = 2715.425, Note = "E7"},
                new SoundProps { Id =90, MinFreq = 2715.435, Frequency = 2793.83, MaxFreq = 2876.895, Note = "F7"},
                new SoundProps { Id =91, MinFreq = 2876.905, Frequency = 2959.96, MaxFreq = 3047.96, Note = "F#7"},
                new SoundProps { Id =92, MinFreq = 3047.97, Frequency = 3135.96, MaxFreq = 3229.2, Note = "G7"},
                new SoundProps { Id =93, MinFreq = 3229.21, Frequency = 3322.44, MaxFreq = 3421.22, Note = "G#7"},
                new SoundProps { Id =94, MinFreq = 3421.23, Frequency = 3520, MaxFreq = 3624.655, Note = "A7"},
                new SoundProps { Id =95, MinFreq = 3624.665, Frequency = 3729.31, MaxFreq = 3840.19, Note = "A#7"},
                new SoundProps { Id =96, MinFreq = 3840.2, Frequency = 3951.07, MaxFreq = 4068.54, Note = "B7"},
                new SoundProps { Id =97, MinFreq = 4068.55, Frequency = 4186.01, MaxFreq = 4310.465, Note = "C8"},
                new SoundProps { Id =98, MinFreq = 4310.475, Frequency = 4434.92, MaxFreq = 4566.775, Note = "C#8"},
                new SoundProps { Id =99, MinFreq = 4566.785, Frequency = 4698.63, MaxFreq = 4838.33, Note = "D8"},
                new SoundProps { Id =100, MinFreq = 4838.34, Frequency = 4978.03, MaxFreq = 5126.035, Note = "D#8"},
                new SoundProps { Id =101, MinFreq = 5126.045, Frequency = 5274.04, MaxFreq = 5430.845, Note = "E8"},
                new SoundProps { Id =102, MinFreq = 5430.855, Frequency = 5587.65, MaxFreq = 5753.78, Note = "F8"},
                new SoundProps { Id =103, MinFreq = 5753.79, Frequency = 5919.91, MaxFreq = 6095.92, Note = "F#8"},
                new SoundProps { Id =104, MinFreq = 6095.93, Frequency = 6271.93, MaxFreq = 6458.405, Note = "G8"},
                new SoundProps { Id =105, MinFreq = 6458.415, Frequency = 6644.88, MaxFreq = 6842.44, Note = "G#8"},
                new SoundProps { Id =106, MinFreq = 6842.45, Frequency = 7040, MaxFreq = 7249.31, Note = "A8"},
                new SoundProps { Id =107, MinFreq = 7249.32, Frequency = 7458.62, MaxFreq = 7680.375, Note = "A#8"},
                new SoundProps { Id =108, MinFreq = 7680.385, Frequency = 7902.13, MaxFreq = 8302.13, Note = "B8"},
            };

            if (notesCount > 0)
            {
                return _database.UpdateAllAsync(notes);
            }
            else
            {
                return _database.InsertAllAsync(notes);
            }
        }

        public Task<int> InsertAllTunings(int tuningCount)
        {


            List<Tuning> tunings = new List<Tuning>
            {
                new Tuning { Id = 1, Name = "Standard", FirstNote = "E2", SecondNote = "A2", ThirdNote = "D3", FourthNote = "G3", FifthNote = "B3", SixthNote = "E4"},
                new Tuning { Id = 2, Name = "Drop D" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "E4"},
                new Tuning { Id = 3, Name = "Half Step Down" , FirstNote = "D#2" , SecondNote = "G#2" , ThirdNote = "C#3" , FourthNote = "F#3" , FifthNote = "A#3" , SixthNote = "D#4"},
                new Tuning { Id = 4, Name = "Full Step Down" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "C3" , FourthNote = "F3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 5, Name = "1 and 1/2 Steps Down" , FirstNote = "C#2" , SecondNote = "F#2" , ThirdNote = "B2" , FourthNote = "E3" , FifthNote = "G#3" , SixthNote = "C#4"},
                new Tuning { Id = 6, Name = "Double Drop D" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "D4"},
                new Tuning { Id = 7, Name = "Drop C" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "C3" , FourthNote = "F3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 8, Name = "Drop C#" , FirstNote = "C#2" , SecondNote = "G#2" , ThirdNote = "C#3" , FourthNote = "F#3" , FifthNote = "A#3" , SixthNote = "D#4"},
                new Tuning { Id = 9, Name = "Drop B" , FirstNote = "B1" , SecondNote = "F#2" , ThirdNote = "B2" , FourthNote = "E3" , FifthNote = "G#3" , SixthNote = "C#4"},
                new Tuning { Id = 10, Name = "Drop A#" , FirstNote = "A#1" , SecondNote = "F2" , ThirdNote = "A#2" , FourthNote = "D#3" , FifthNote = "G3" , SixthNote = "C4"},
                new Tuning { Id = 11, Name = "Drop A" , FirstNote = "A1" , SecondNote = "E2" , ThirdNote = "A2" , FourthNote = "D3" , FifthNote = "F#3" , SixthNote = "B3"},
                new Tuning { Id = 12, Name = "Open D" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "F#2" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 13, Name = "Open D Minor" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "F3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 14, Name = "Open G" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "D4"},
                new Tuning { Id = 15, Name = "Open G Minor" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "A#3" , SixthNote = "D4"},
                new Tuning { Id = 16, Name = "Open C" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "C3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "E4"},
                new Tuning { Id = 17, Name = "Open C#" , FirstNote = "C#2" , SecondNote = "F#2" , ThirdNote = "B3" , FourthNote = "E3" , FifthNote = "G#3" , SixthNote = "C#4"},
                new Tuning { Id = 18, Name = "Open C Minor" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "C3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "D#4"},
                new Tuning { Id = 19, Name = "Open E7" , FirstNote = "E2" , SecondNote = "G#2" , ThirdNote = "D3" , FourthNote = "E3" , FifthNote = "B3" , SixthNote = "E4"},
                new Tuning { Id = 20, Name = "Open E Minor7" , FirstNote = "E2" , SecondNote = "B2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "E4"},
                new Tuning { Id = 21, Name = "Open G Major7" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "F#3" , FifthNote = "B3" , SixthNote = "D4"},
                new Tuning { Id = 22, Name = "Open A Minor" , FirstNote = "E2" , SecondNote = "A2" , ThirdNote = "E3" , FourthNote = "A3" , FifthNote = "C4" , SixthNote = "E4"},
                new Tuning { Id = 23, Name = "Open A Minor7" , FirstNote = "E2" , SecondNote = "A2" , ThirdNote = "E3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "E4"},
                new Tuning { Id = 24, Name = "Open E" , FirstNote = "E2" , SecondNote = "B2" , ThirdNote = "E3" , FourthNote = "G#3" , FifthNote = "B3" , SixthNote = "E4"},
                new Tuning { Id = 25, Name = "Open A" , FirstNote = "E2" , SecondNote = "A2" , ThirdNote = "C#3" , FourthNote = "E3" , FifthNote = "A3" , SixthNote = "E4"},
                new Tuning { Id = 26, Name = "C Tuning" , FirstNote = "C2" , SecondNote = "F2" , ThirdNote = "A#2" , FourthNote = "D#3" , FifthNote = "G3" , SixthNote = "C4"},
                new Tuning { Id = 27, Name = "C# Tuning" , FirstNote = "C#2" , SecondNote = "F#2" , ThirdNote = "B2" , FourthNote = "E3" , FifthNote = "G#3" , SixthNote = "C#4"},
                new Tuning { Id = 28, Name = "Bb Tuning" , FirstNote = "A#1" , SecondNote = "D#2" , ThirdNote = "G#2" , FourthNote = "C#3" , FifthNote = "F3" , SixthNote = "A#3"},
                new Tuning { Id = 29, Name = "A to A (Baritone)" , FirstNote = "A1" , SecondNote = "D2" , ThirdNote = "G2" , FourthNote = "C3" , FifthNote = "E3" , SixthNote = "A3"},
                new Tuning { Id = 30, Name = "D A D D D D" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "D3" , FifthNote = "D4" , SixthNote = "D4"},
                new Tuning { Id = 31, Name = "C G D G B D " , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "D4"},
                new Tuning { Id = 32, Name = "C G D G B E" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "E4"},
                new Tuning { Id = 33, Name = "D A D E A D" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "E3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 34, Name = "D G D G A D" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 35, Name = "Open Dsus2" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 36, Name = "Open Gsus2" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "D4"},
                new Tuning { Id = 37, Name = "G6" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "E4"},
                new Tuning { Id = 38, Name = "Modal G" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "D4"},
                new Tuning { Id = 39, Name = "Overtone" , FirstNote = "C3" , SecondNote = "E3" , ThirdNote = "G3" , FourthNote = "A#3" , FifthNote = "C4" , SixthNote = "D4"},
                new Tuning { Id = 40, Name = "Pentatotnic" , FirstNote = "A2" , SecondNote = "C3" , ThirdNote = "D3" , FourthNote = "E3" , FifthNote = "G3" , SixthNote = "A4"},
                new Tuning { Id = 41, Name = "Minor Third" , FirstNote = "C3" , SecondNote = "D#3" , ThirdNote = "F#3" , FourthNote = "A3" , FifthNote = "C4" , SixthNote = "D#4"},
                new Tuning { Id = 42, Name = "Major Third" , FirstNote = "C3" , SecondNote = "E3" , ThirdNote = "G#3" , FourthNote = "C4" , FifthNote = "E4" , SixthNote = "G#4"},
                new Tuning { Id = 43, Name = "All Fourths" , FirstNote = "E2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "F4"},
                new Tuning { Id = 44, Name = "Augmented Fourths" , FirstNote = "C2" , SecondNote = "F#2" , ThirdNote = "C3" , FourthNote = "F#3" , FifthNote = "C4" , SixthNote = "F#4"},
                new Tuning { Id = 45, Name = "Slow Motion" , FirstNote = "D2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "F3" , FifthNote = "C4" , SixthNote = "D4"},
                new Tuning { Id = 46, Name = "Admiral" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "C4"},
                new Tuning { Id = 47, Name = "Buzzard" , FirstNote = "C2" , SecondNote = "F2" , ThirdNote = "C3" , FourthNote = "G3" , FifthNote = "A#3" , SixthNote = "F4"},
                new Tuning { Id = 48, Name = "Face" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 49, Name = "Four and Twenty" , FirstNote = "D2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "D3" , FifthNote = "A3" , SixthNote = "D4"},
                new Tuning { Id = 50, Name = "Ostrich" , FirstNote = "D2" , SecondNote = "D3" , ThirdNote = "D3" , FourthNote = "D3" , FifthNote = "D4" , SixthNote = "D4"},
                new Tuning { Id = 51, Name = "Capo 200" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "D#3" , FifthNote = "D4" , SixthNote = "D#4"},
                new Tuning { Id = 52, Name = "Balalaika" , FirstNote = "E2" , SecondNote = "A2" , ThirdNote = "D3" , FourthNote = "E3" , FifthNote = "E3" , SixthNote = "A3"},
                new Tuning { Id = 53, Name = "Cittern One" , FirstNote = "C2" , SecondNote = "F2" , ThirdNote = "C3" , FourthNote = "F3" , FifthNote = "C4" , SixthNote = "D4"},
                new Tuning { Id = 54, Name = "Cittern Two" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "C3" , FourthNote = "G3" , FifthNote = "C4" , SixthNote = "G4"},
                new Tuning { Id = 55, Name = "Dobro" , FirstNote = "G2" , SecondNote = "B2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "D4"},
                new Tuning { Id = 56, Name = "Lefty" , FirstNote = "E4" , SecondNote = "B3" , ThirdNote = "G3" , FourthNote = "D3" , FifthNote = "A2" , SixthNote = "E2"},
                new Tuning { Id = 57, Name = "Mandoguitar" , FirstNote = "C2" , SecondNote = "G2" , ThirdNote = "D3" , FourthNote = "A3" , FifthNote = "E4" , SixthNote = "B4"},
                new Tuning { Id = 58, Name = "Rusty Cage" , FirstNote = "B1" , SecondNote = "E2" , ThirdNote = "D3" , FourthNote = "G3" , FifthNote = "B3" , SixthNote = "E4"}
            };

            if (tuningCount > 0)
            {
                return _database.UpdateAllAsync(tunings);
            }
            else
            {
                return _database.InsertAllAsync(tunings);
            }
        }

        public Task<int> InsertAllScales(int scalesCount)
        {
            List<Scales> scales = new List<Scales>
            {
                new Scales { Id = 1, Name ="Major Suspended 4th Chord", ScalesNotes = "C D F G"},
                new Scales { Id = 2, Name ="Major b7 Suspend 4th Chord", ScalesNotes = "C F G Bb"},
                new Scales { Id = 3, Name ="Major Pentatonic", ScalesNotes = "C D E G A"},
                new Scales { Id = 4, Name ="Ritusen Japan, Scottish Pentatonic", ScalesNotes = "C D F G A"},
                new Scales { Id = 5, Name ="Egyptian \\ Suspended Pentatonic", ScalesNotes = "C D F G Bb"},
                new Scales { Id = 6, Name ="Blues Pentatonic Minor, Hard Japan", ScalesNotes = "C Eb F G Bb"},
                new Scales { Id = 7, Name ="Major 7-b5 Chord \\ Messiaen Truncated Mode", ScalesNotes = "C Eb G Bb"},
                new Scales { Id = 8, Name ="Minor b7 Chord", ScalesNotes = "C Eb G Bb"},
                new Scales { Id = 9, Name ="Major Chord", ScalesNotes = "C E G"},
                new Scales { Id = 10, Name ="Eskimo Tetratonic", ScalesNotes = "C D E G"},
                new Scales { Id = 11, Name ="Lydian Hexatonic", ScalesNotes = "C D E G A B"},
                new Scales { Id = 12, Name ="Scottish Hexatonic", ScalesNotes = "C D E F G A"},
                new Scales { Id = 13, Name ="Mixolydian Hexatonic", ScalesNotes = "C D F G A Bb"},
                new Scales { Id = 14, Name ="Phrygian Hexatonic", ScalesNotes = "C Eb F G Ab Bb"},
                new Scales { Id = 15, Name ="Ritsu", ScalesNotes = "C Db Eb F Ab Bb"},
                new Scales { Id = 16, Name ="Minor Pentachord", ScalesNotes = "C D Eb F G"},
                new Scales { Id = 17, Name ="Major 7 Chord", ScalesNotes = "C E G B"},
                new Scales { Id = 18, Name ="Phrygian Tetrachord", ScalesNotes = "C Db Eb F"},
                new Scales { Id = 19, Name ="Dorian Tetrachord", ScalesNotes = "C D Eb F"},
                new Scales { Id = 20, Name ="Major Tetrachord", ScalesNotes = "C D E F"},
                new Scales { Id = 21, Name ="Warao Tetratonic", ScalesNotes = "C D Eb Bb"},
                new Scales { Id = 22, Name ="Oriental", ScalesNotes = "C D F A Bb"},
                new Scales { Id = 23, Name ="Major Pentachord", ScalesNotes = "C D E F G"},
                new Scales { Id = 24, Name ="Han-Kumo?", ScalesNotes = "C D F G Ab"},
                new Scales { Id = 25, Name ="Lydian, Kalyan F to E  ", ScalesNotes = "C D E F# G A B"},
                new Scales { Id = 26, Name ="Ionian, Major, Bilaval  C to B   ", ScalesNotes = "C D E F G A B"},
                new Scales { Id = 27, Name ="Mixolydian, Khamaj G to F  ", ScalesNotes = "C D E F G A Bb"},
                new Scales { Id = 28, Name ="Dorian, Kafi  D to C  ", ScalesNotes = "C D Eb F G A Bb"},
                new Scales { Id = 29, Name ="Aeolian Natural Minor Asavari A to G", ScalesNotes = "C D Eb F G Ab Bb"},
                new Scales { Id = 30, Name ="Phrygian, Bhairavi  E to D  ", ScalesNotes = "C Db Eb F G Ab Bb"},
                new Scales { Id = 31, Name ="Locrian  - B to A  ", ScalesNotes = "C Db Eb F Gb Ab Bb"},
                new Scales { Id = 32, Name ="Raga Bagesri", ScalesNotes = "C D Eb F A Bb"},
                new Scales { Id = 33, Name ="Raga Gandharavam", ScalesNotes = "C Db Eb F G Bb"},
                new Scales { Id = 34, Name ="Dorian Pentatonic, Kumoi Japan", ScalesNotes = "C D Eb G A"},
                new Scales { Id = 35, Name ="Kokin-Joshi, Soft Ascend Japan", ScalesNotes = "C Db F G Bb"},
                new Scales { Id = 36, Name ="Raga Jayakauns", ScalesNotes = "C Eb F Gb Bb"},
                new Scales { Id = 37, Name ="Diminished Chord", ScalesNotes = "C Eb Gb"},
                new Scales { Id = 39, Name ="Whole-Tone Tetramirror", ScalesNotes = "C D E F#"},
                new Scales { Id = 40, Name ="Raga Valaji", ScalesNotes = "C E G A Bb"},
                new Scales { Id = 41, Name ="Raga Abhogi", ScalesNotes = "C D Eb F A"},
                new Scales { Id = 42, Name ="Raga Rukmangi \\ Pelog 2", ScalesNotes = "C Db Eb G Bb"},
                new Scales { Id = 43, Name ="Major b7 Chord", ScalesNotes = "C E G Bb"},
                new Scales { Id = 44, Name ="Kung", ScalesNotes = "C D E F# A"},
                new Scales { Id = 45, Name ="Dominant Pentatonic", ScalesNotes = "C D E G Bb"},
                new Scales { Id = 46, Name ="Minor 6th Added", ScalesNotes = "C Eb F G A"},
                new Scales { Id = 47, Name ="Raga Harikauns", ScalesNotes = "C Eb Gb Ab Bb"},
                new Scales { Id = 48, Name ="Honchoshi Plagal Form", ScalesNotes = "C Db Eb F Gb Bb"},
                new Scales { Id = 49, Name ="Chinese", ScalesNotes = "C E F# G B"},
                new Scales { Id = 50, Name ="Hindolita", ScalesNotes = "C E F A B"},
                new Scales { Id = 51, Name ="Hirajoshi Japan", ScalesNotes = "C D Eb G Ab"},
                new Scales { Id = 52, Name ="Soft Descend Japan", ScalesNotes = "C Db F G Ab"},
                new Scales { Id = 53, Name ="Iwato Japan", ScalesNotes = "C Db F Gb Bb"},
                new Scales { Id = 54, Name ="Japanese \\ Sakura Pentatonic", ScalesNotes = "C Db F G Ab"},
                new Scales { Id = 55, Name ="Locrian PentaMirror", ScalesNotes = "C Db Eb F Gb"},
                new Scales { Id = 56, Name ="Genus Secundum", ScalesNotes = "C E F G A B"},
                new Scales { Id = 57, Name ="Raga Trimurti", ScalesNotes = "C D Eb G Ab Bb"},
                new Scales { Id = 58, Name ="Raga Vaijayanti", ScalesNotes = "C D F# G B"},
                new Scales { Id = 59, Name ="Ionian Pentatonic", ScalesNotes = "C E F G B"},
                new Scales { Id = 60, Name ="Raga Khamaji Durga", ScalesNotes = "C E F A Bb"},
                new Scales { Id = 61, Name ="Balinese \\ Pelog 1", ScalesNotes = "C Db Eb G Ab"},
                new Scales { Id = 62, Name ="Lydian Pentachord", ScalesNotes = "C D E F# G"},
                new Scales { Id = 63, Name ="Raga Shri Kalyan", ScalesNotes = "C D F# G A"},
                new Scales { Id = 64, Name ="Raga Desh", ScalesNotes = "C D F G B"},
                new Scales { Id = 65, Name ="Mixolydian Pentatonic", ScalesNotes = "C E F G Bb"},
                new Scales { Id = 66, Name ="Raga Chandrakauns Kafi", ScalesNotes = "C Eb F A Bb"},
                new Scales { Id = 67, Name ="Raga Yamuna Kalyani", ScalesNotes = "C D E F# G A"},
                new Scales { Id = 68, Name ="Major Lydian", ScalesNotes = "C D E F F# G A B"},
                new Scales { Id = 69, Name ="Dominant Bebop", ScalesNotes = "C D E F G A Bb B"},
                new Scales { Id = 70, Name ="Altered Pentatonic", ScalesNotes = "C Db F G A"},
                new Scales { Id = 71, Name ="Chromatic TriMirror", ScalesNotes = "C C# D"},
                new Scales { Id = 72, Name ="Raga Vijayasri", ScalesNotes = "C C# D F# G B"},
                new Scales { Id = 74, Name ="Raga Tilang", ScalesNotes = "C E F G Bb B"},
                new Scales { Id = 75, Name ="Jazz Minor Inverse \\ Javanese \\ Dorian bII", ScalesNotes = "C Db Eb F G A Bb"},
                new Scales { Id = 76, Name ="Raga Zilaf", ScalesNotes = "C E F G Ab"},
                new Scales { Id = 77, Name ="Hindi 5 flats & bIV", ScalesNotes = "C Db Eb Fb Gb Ab Bb"},
                new Scales { Id = 78, Name ="Augmented Chord \\ 4 Semitones", ScalesNotes = "C E G#"},
                new Scales { Id = 79, Name ="Harmonic Minor Tetrachord", ScalesNotes = "C D Eb Gb"},
                new Scales { Id = 80, Name ="Raga Paraju", ScalesNotes = "C E F G Ab B"},
                new Scales { Id = 81, Name ="Hawaiian", ScalesNotes = "C D Eb G A B"},
                new Scales { Id = 82, Name ="Messiaen Truncated Mode 6", ScalesNotes = "C D F# G#"},
                new Scales { Id = 83, Name ="Raga Vutari", ScalesNotes = "C E F# G A Bb"},
                new Scales { Id = 84, Name ="Neapolitan Minor Mode", ScalesNotes = "C C# D E F# G# A"},
                new Scales { Id = 85, Name ="Raga Nata", ScalesNotes = "C Eb F G B"},
                new Scales { Id = 86, Name ="Takemitsu Tree Line Mode 2", ScalesNotes = "C D Eb Gb Ab Bb"},
                new Scales { Id = 87, Name ="Eskimo Hexatonic 2", ScalesNotes = "C D E F# G# A"},
                new Scales { Id = 88, Name ="Lydian Augmented, Hindi #IV & #V", ScalesNotes = "C D E F# G# A B"},
                new Scales { Id = 89, Name ="Lydian Dominant, Overtone, Bartok, Hindi", ScalesNotes = "C D E F# G A Bb"},
                new Scales { Id = 90, Name ="Minor Melodic", ScalesNotes = "C D Eb F G A B"},
                new Scales { Id = 91, Name ="Major Minor, Hindu bVI & bVII", ScalesNotes = "C D E F G Ab Bb"},
                new Scales { Id = 92, Name ="Hindi bII bIII bVII", ScalesNotes = "C Db Eb F# G A Bb"},
                new Scales { Id = 93, Name ="Minor Locrian, Hindi 3 flats and bV", ScalesNotes = "C D Eb F Gb Ab Bb"},
                new Scales { Id = 94, Name ="Lydian #2 Hexatonic", ScalesNotes = "C D# E G A B"},
                new Scales { Id = 95, Name ="Chromatic Phrygian Inverse", ScalesNotes = "C C# D E G G# A"},
                new Scales { Id = 96, Name ="Chromatic Hypophrygian Inverse", ScalesNotes = "C C# D F F# G A"},
                new Scales { Id = 97, Name ="Blues Octatonic", ScalesNotes = "C D Eb F F# G A Bb"},
                new Scales { Id = 98, Name ="Locrian bb7", ScalesNotes = "C Db Eb F Gb Ab A"},
                new Scales { Id = 99, Name ="Alternating TetraMirror", ScalesNotes = "C Db D# E"},
                new Scales { Id = 100, Name ="Scriabin", ScalesNotes = "C Db E G A"},
                new Scales { Id = 101, Name ="Raga Latika", ScalesNotes = "C D E G Ab B"},
                new Scales { Id = 102, Name ="Diminished 7th Chord \\ 3 Semitones", ScalesNotes = "C Eb Gb A"},
                new Scales { Id = 103, Name ="Pyramid Hexatonic", ScalesNotes = "C D Eb F Gb A"},
                new Scales { Id = 104, Name ="Aeolian Flat 1", ScalesNotes = "C D# E F# G# A B"},
                new Scales { Id = 105, Name ="Lydian Diminished", ScalesNotes = "C D Eb F# G A B"},
                new Scales { Id = 106, Name ="Harmonic Major 1 \\ Ethiopian \\ Nat Bhairava", ScalesNotes = "C D E F G Ab B"},
                new Scales { Id = 107, Name ="Harmonic Minor Inverse or Bhairav", ScalesNotes = "C Db E F G A Bb"},
                new Scales { Id = 108, Name ="Dorian b5", ScalesNotes = "C D Eb F Gb A Bb"},
                new Scales { Id = 109, Name ="Raga Vijayanagari", ScalesNotes = "C D Eb F# G A"},
                new Scales { Id = 110, Name ="", ScalesNotes = ""},
                new Scales { Id = 111, Name ="Chromatic PentaMirror", ScalesNotes = "C C# D D# E"},
                new Scales { Id = 112, Name ="Blues #V", ScalesNotes = "C Eb F F# B"},
                new Scales { Id = 113, Name ="Blues Minor Maj7", ScalesNotes = "C Eb F F# G B"},
                new Scales { Id = 114, Name ="Chromatic Mixolydian", ScalesNotes = "C C# D E F# G Bb"},
                new Scales { Id = 115, Name ="Romanian Bacovia", ScalesNotes = "C E F G# B"},
                new Scales { Id = 116, Name ="Double-Phrygian Hexatonic", ScalesNotes = "C Db Eb F Gb A"},
                new Scales { Id = 117, Name ="Lydian #2", ScalesNotes = "C D# E F# G A B"},
                new Scales { Id = 118, Name ="Harmonic Major 2 \\ Ionian #5", ScalesNotes = "C D E F G# A B"},
                new Scales { Id = 119, Name ="Romanian, Gnossiennes", ScalesNotes = "C D Eb F# G A Bb"},
                new Scales { Id = 120, Name ="Harmonic Minor", ScalesNotes = "C D Eb F G Ab B"},
                new Scales { Id = 121, Name ="Phrygian Dominant, Dorico Flamenco, Avaha", ScalesNotes = "C Db E F G Ab Bb"},
                new Scales { Id = 122, Name ="Locrian Natural Maj 6, Pseudo Turkish", ScalesNotes = "C Db Eb F Gb A Bb"},
                new Scales { Id = 123, Name ="Chromatic DecaMirror", ScalesNotes = "C C# D D# E F F# G G# A"},
                new Scales { Id = 124, Name ="Chromatic Hypodorian", ScalesNotes = "C D D# E G G# A"},
                new Scales { Id = 125, Name ="Chromatic Dorian", ScalesNotes = "C C# D F G G# A"},
                new Scales { Id = 126, Name ="Major Blues", ScalesNotes = "C D D# E G A"},
                new Scales { Id = 127, Name ="Blues Minor", ScalesNotes = "C Eb F F# G Bb"},
                new Scales { Id = 128, Name ="Blues Heptatonic", ScalesNotes = "C Eb F F# G A Bb"},
                new Scales { Id = 129, Name ="Major Bebop Heptatonic", ScalesNotes = "C D E F G G# A"},
                new Scales { Id = 130, Name ="Blues Modified", ScalesNotes = "C D Eb F F# G Bb"},
                new Scales { Id = 131, Name ="Chromatic Permuted Diatonic Dorian", ScalesNotes = "C C# D E F G G# A B"},
                new Scales { Id = 132, Name ="Youlan", ScalesNotes = "C C# D E F F# G A Bb"},
                new Scales { Id = 133, Name ="Major Bebop", ScalesNotes = "C D E F G G# A B"},
                new Scales { Id = 134, Name ="Chromatic Bebop", ScalesNotes = "C Db D E F G A Bb B"},
                new Scales { Id = 135, Name ="Prometheus", ScalesNotes = "C D E Gb A Bb"},
                new Scales { Id = 136, Name ="Raga Vasanta", ScalesNotes = "C Db E F A B"},
                new Scales { Id = 137, Name ="Mixolydian b5", ScalesNotes = "C D E F Gb A Bb"},
                new Scales { Id = 138, Name ="Chromatic TetraMirror", ScalesNotes = "C C# D Eb"},
                new Scales { Id = 139, Name ="1 & 3 tones", ScalesNotes = "C D G# Bb E F#"},
                new Scales { Id = 140, Name ="3 tones & 1", ScalesNotes = "C F# G# D E Bb"},
                new Scales { Id = 141, Name ="Whole-Tone \\ Anhemitonic Hexatonic", ScalesNotes = "C D E F# G# Bb"},
                new Scales { Id = 142, Name ="Raga Jyoti", ScalesNotes = "C E F# G Ab Bb"},
                new Scales { Id = 143, Name ="Leading Whole-Tone", ScalesNotes = "C D E F# G# A# B"},
                new Scales { Id = 144, Name ="Lydian Minor, Stravinski", ScalesNotes = "C D E F# G Ab Bb"},
                new Scales { Id = 145, Name ="Neapolitan Major", ScalesNotes = "C Db Eb F G A B"},
                new Scales { Id = 146, Name ="Major Locrian", ScalesNotes = "C D E F Gb Ab Bb"},
                new Scales { Id = 147, Name ="Center-Cluster PentaMirror", ScalesNotes = "C D# E F G#"},
                new Scales { Id = 148, Name ="Prometheus Neapolitan", ScalesNotes = "C Db E Gb A Bb"},
                new Scales { Id = 149, Name ="Hungarian Minor", ScalesNotes = "C D Eb F# G Ab B"},
                new Scales { Id = 150, Name ="Hungarian Folk or Byzantine", ScalesNotes = "C Db E F G Ab B"},
                new Scales { Id = 151, Name ="Oriental 1", ScalesNotes = "C Db E F Gb A Bb"},
                new Scales { Id = 152, Name ="Raga Vijayavasanta", ScalesNotes = "C E F# G A# B"},
                new Scales { Id = 153, Name ="Chromatic HeptaMirror", ScalesNotes = "C C# D D# E F F#"},
                new Scales { Id = 154, Name ="Chromatic HexaMirror", ScalesNotes = "C C# D D# E F"},
                new Scales { Id = 155, Name ="Algerian", ScalesNotes = "C D Eb F F# G Ab B"},
                new Scales { Id = 156, Name ="Chaio", ScalesNotes = "C D F G# Bb"},
                new Scales { Id = 157, Name ="Mixolydian Augmented", ScalesNotes = "C D E F G# A Bb"},
                new Scales { Id = 158, Name ="Hungarian Gypsy, Damian Emmanuel", ScalesNotes = "C D Eb F# G Ab Bb"},
                new Scales { Id = 159, Name ="Neapolitan Minor", ScalesNotes = "C Db Eb F G Ab B"},
                new Scales { Id = 160, Name ="Chromatic NonaMirror", ScalesNotes = "C C# D D# E F F# G G#"},
                new Scales { Id = 161, Name ="Chromatic OctaMirror", ScalesNotes = "C C# D D# E F F# G"},
                new Scales { Id = 162, Name ="Major & Minor mixed", ScalesNotes = "C D D# E F G G# A A# B"},
                new Scales { Id = 163, Name ="Adonai Malakh", ScalesNotes = "C C# D Eb F G A Bb"},
                new Scales { Id = 164, Name ="Houzam", ScalesNotes = "C D# E F G A B"},
                new Scales { Id = 165, Name ="Chromatic Phrygian", ScalesNotes = "C D# E F G# A# B"},
                new Scales { Id = 166, Name ="Chromatic Mixolydian Inverse", ScalesNotes = "C D F F# G A# B"},
                new Scales { Id = 167, Name ="Marva or Marvi", ScalesNotes = "C Db E F# G A B"},
                new Scales { Id = 168, Name ="Messiaen Truncated Mode 5", ScalesNotes = "C Db F# G"},
                new Scales { Id = 169, Name ="Messiaen Truncated Mode 5 Inverse", ScalesNotes = "C F Gb B"},
                new Scales { Id = 170, Name ="Balinese Pentachord", ScalesNotes = "C Db E F# G"},
                new Scales { Id = 171, Name ="Messiaen Mode 5", ScalesNotes = "C C# D F# G Ab"},
                new Scales { Id = 172, Name ="Romanian Major, Purvi bVII", ScalesNotes = "C Db E F# G A Bb"},
                new Scales { Id = 173, Name ="Messiaen Mode 4", ScalesNotes = "C C# D Eb F# G G# A"},
                new Scales { Id = 174, Name ="Messiaen Truncated Mode 2", ScalesNotes = "C Db Eb F# G A"},
                new Scales { Id = 175, Name ="Japanese Pentachord", ScalesNotes = "C Db Eb F# G"},
                new Scales { Id = 176, Name ="Messiaen Mode 6", ScalesNotes = "C C# D E F# G Ab Bb"},
                new Scales { Id = 177, Name ="Takemitsu Tree Line Mode 1", ScalesNotes = "C D Eb Gb Ab B"},
                new Scales { Id = 178, Name ="Hungarian Major", ScalesNotes = "C D# E F# G A Bb"},
                new Scales { Id = 179, Name ="Todi bVII", ScalesNotes = "C Db Eb F# G A Bb"},
                new Scales { Id = 180, Name ="Messiaen Mode 7", ScalesNotes = "C C# D D# E F# G G# A Bb"},
                new Scales { Id = 181, Name ="Zirafkend", ScalesNotes = "C D Eb F G G# A B"},
                new Scales { Id = 182, Name ="untitled Nonatonic 1", ScalesNotes = "C C# D Eb F F# G G# A"},
                new Scales { Id = 183, Name ="Minor Bebop Heptatonic", ScalesNotes = "C D D# E G A Bb"},
                new Scales { Id = 184, Name ="Blues Phrygian", ScalesNotes = "C Db Eb F F# G Bb"},
                new Scales { Id = 185, Name ="Chromatic Hypolydian, Puravi bVI", ScalesNotes = "C Db E F# G Ab B"},
                new Scales { Id = 186, Name ="Chromatic Lydian", ScalesNotes = "C Db E F Gb A B"},
                new Scales { Id = 187, Name ="Hungarian Minor b2", ScalesNotes = "C C# D Eb F# G Ab B"},
                new Scales { Id = 188, Name ="Harmonic Neapolitan Minor", ScalesNotes = "C C# D Eb F G Ab B"},
                new Scales { Id = 189, Name ="Blues with Leading Tone", ScalesNotes = "C Eb F F# G A# B"},
                new Scales { Id = 190, Name ="Chromatic Dorian Inverse", ScalesNotes = "C D# E F G A# B"},
                new Scales { Id = 191, Name ="Chromatic Hypodorian Inverse", ScalesNotes = "C D# E F G# A Bb"},
                new Scales { Id = 192, Name ="Chromatic Lydian Inverse, Todi bVI", ScalesNotes = "C Db Eb F# G Ab B"},
                new Scales { Id = 193, Name ="Half-Diminished Bebop", ScalesNotes = "C Db Eb F# G Ab B"},
                new Scales { Id = 194, Name ="Chromatic Hypolydian Inverse, Persian", ScalesNotes = "C Db E F Gb Ab B"},
                new Scales { Id = 195, Name ="Raga Madhuri", ScalesNotes = "C E F G A A# B"},
                new Scales { Id = 196, Name ="Raga Malkauns", ScalesNotes = "C Eb F G# Bb"},
                new Scales { Id = 197, Name ="Raga Megh", ScalesNotes = "C D F G A# B"},
                new Scales { Id = 198, Name ="Rock 'n' Roll", ScalesNotes = "C D# E F G A Bb"},
                new Scales { Id = 199, Name ="Chromatic UndecaMirror", ScalesNotes = "C C# D D# E F F# G G# A Bb"},
                new Scales { Id = 200, Name ="Blues Enneatonic", ScalesNotes = "C D D# E F F# G A Bb"},
                new Scales { Id = 201, Name ="Chromatic Diatonic Dorian", ScalesNotes = "C C# D Eb F G G# A Bb"},
                new Scales { Id = 202, Name ="Minor Bebop", ScalesNotes = "C D D# E F G A Bb"},
                new Scales { Id = 203, Name ="Dorian Aeolian", ScalesNotes = "C D Eb F G G# A Bb"},
                new Scales { Id = 204, Name ="Phrygian Aeolian", ScalesNotes = "C C# D Eb F G Ab Bb"},
                new Scales { Id = 205, Name ="Phrygian Locrian", ScalesNotes = "C Db Eb F F# G Ab Bb"},
                new Scales { Id = 206, Name ="Kiourdi", ScalesNotes = "C D Eb F F# G G# A Bb"},
                new Scales { Id = 207, Name ="Minor Pentatonic with Leading Tones", ScalesNotes = "C D D# E F F# G A A# B"},
                new Scales { Id = 208, Name ="Lydian Mixolydian", ScalesNotes = "C D E F F# G A A# B"},
                new Scales { Id = 209, Name ="Houseini", ScalesNotes = "C D D# E F G G# A Bb"},
                new Scales { Id = 210, Name ="Example of Slendro", ScalesNotes = "C D F G A"},
                new Scales { Id = 211, Name ="Whole tone alternate", ScalesNotes = "C D E F# G# A# B#"},
                new Scales { Id = 212, Name ="Oriental Pentacluster", ScalesNotes = "C C# D F Gb"},
                new Scales { Id = 213, Name ="Augmented \\ Messiaen Truncated Mode 3", ScalesNotes = "C D# E G Ab B"},
                new Scales { Id = 214, Name ="Messiaen Truncated Mode 3 \\ Half-Augmented", ScalesNotes = "C Db E F G# A"},
                new Scales { Id = 215, Name ="Blues PentaCluster", ScalesNotes = "C C# D Eb Gb"},
                new Scales { Id = 216, Name ="Raga Vasantabhairavi", ScalesNotes = "C Db E F G# Bb"},
                new Scales { Id = 217, Name ="Raga Viyogavarali", ScalesNotes = "C Db Eb F G# B"},
                new Scales { Id = 218, Name ="Sabach", ScalesNotes = "C D D# E G Ab Bb"},
                new Scales { Id = 219, Name ="Raga Mian Ki Malhar", ScalesNotes = "C D Eb F G A A# B"},
                new Scales { Id = 220, Name ="Full Minor", ScalesNotes = "C D Eb F G G# A A# B"},
                new Scales { Id = 221, Name ="Magen Abot", ScalesNotes = "C Db D# E F# G# A B"},
                new Scales { Id = 222, Name ="Blues Dorian Hexatonic", ScalesNotes = "C Db D# E G A"},
                new Scales { Id = 223, Name ="Nohkan", ScalesNotes = "C D F Gb G# A B"},
                new Scales { Id = 224, Name ="Shostakovich", ScalesNotes = "C Db D# E F# G A B"},
                new Scales { Id = 225, Name ="Spanish Pentacluster", ScalesNotes = "C Db D# E F"},
                new Scales { Id = 226, Name ="Messiaen Mode 3 Inverse", ScalesNotes = "C D D# E F# G Ab A# B"},
                new Scales { Id = 227, Name ="Genus Chromaticum", ScalesNotes = "C Db D# E F G G# A B"},
                new Scales { Id = 228, Name ="Messiaen Mode 3", ScalesNotes = "C C# D E F Gb G# A Bb"},
                new Scales { Id = 229, Name ="Symmetrical Nonatonic", ScalesNotes = "C C# D E F# G Ab A# B"},
                new Scales { Id = 230, Name ="Half-Diminished \\ Symmetric \\ Blues", ScalesNotes = "C Db D# E F# G A Bb"},
                new Scales { Id = 231, Name ="Diminished", ScalesNotes = "C D Eb F Gb G# A B"},
                new Scales { Id = 232, Name ="JG Octatonic", ScalesNotes = "C Db D# E F G A Bb"},
                new Scales { Id = 233, Name ="Nonatonic 2", ScalesNotes = "C Db D# E F F# G A Bb"},
                new Scales { Id = 234, Name ="Gipsy Hexatonic \\ Raga Kalakanti", ScalesNotes = "C Db F Gb G# A Bb"},
                new Scales { Id = 235, Name ="Indian \\ Phrygian dim 4th", ScalesNotes = "C Db D# E G Ab Bb"},
                new Scales { Id = 236, Name ="Utility Minor", ScalesNotes = "C D Eb F G Ab A# B"},
                new Scales { Id = 237, Name ="Phrygian Major \\ Flamenco \\ Spanish Phrygian", ScalesNotes = "C Db D# E F G Ab Bb"},
                new Scales { Id = 238, Name ="Ultra Locrian", ScalesNotes = "C Db D# E F# G# A"},
                new Scales { Id = 239, Name ="Enigmatic Major, Verdi Enigmatic ", ScalesNotes = "C Db E F# G# A# B"},
                new Scales { Id = 240, Name ="Verdi Enigmatic Descending", ScalesNotes = "C Db E F G# A# B"},
                new Scales { Id = 241, Name ="Enigmatic Minor", ScalesNotes = "C Db Eb F# G# A# B"},
                new Scales { Id = 242, Name ="Spanish Heptatonic", ScalesNotes = "C D# E F Gb Ab Bb"},
                new Scales { Id = 243, Name ="Moorish Phrygian", ScalesNotes = "C Db D# E F G Ab A# B"},
                new Scales { Id = 244, Name ="Maqam Hijaz", ScalesNotes = "C Db E F G Ab A# B"},
                new Scales { Id = 245, Name ="Maqam Shadd'araban", ScalesNotes = "C Db D# E F Gb A Bb"},
                new Scales { Id = 246, Name ="Neveseri", ScalesNotes = "C Db Eb F# G Ab A# B"},
                new Scales { Id = 247, Name ="Superlocrian \\ Diminished Whole-Tone", ScalesNotes = "C Db D# E Gb Ab Bb"},
                new Scales { Id = 248, Name ="Spanish 8 Tones", ScalesNotes = "C Db D# E F Gb Ab Bb"},
                new Scales { Id = 249, Name ="Messiaen Mode 5 Inverse", ScalesNotes = "C E F Gb A# B"},
                new Scales { Id = 250, Name ="Messiaen Mode 6 Inverse", ScalesNotes = "C D E F Gb G# A# B"},
                new Scales { Id = 251, Name ="Messiaen Mode 7 Inverse", ScalesNotes = "C D D# E F Gb G# A A# B"},
                new Scales { Id = 252, Name ="Messiaen Mode 4 Inverse", ScalesNotes = "C D# E F Gb A A# B"},
                new Scales { Id = 253, Name ="Oriental 2", ScalesNotes = "C Db E F Gb A A# B"},
                new Scales { Id = 254, Name ="Verdi Enigmatic", ScalesNotes = "C Db E F Gb Ab A# B"},
                new Scales { Id = 255, Name ="Prokofiev", ScalesNotes = "C Db Eb F Gb Ab A# B"},
                new Scales { Id = 256, Name ="Example Of Pelog", ScalesNotes = "C Cx Fb F# G Ab B"},
                new Scales { Id = 257, Name ="C Major", ScalesNotes = "C D E F G A B"},
                new Scales { Id = 258, Name ="C Minor", ScalesNotes = "C D Eb F G Ab Bb"},
                new Scales { Id = 259, Name ="C# Major", ScalesNotes = "C# D# E# F# G# A# B#"},
                new Scales { Id = 260, Name ="C# Minor", ScalesNotes = "C# D# E F# G# A B"},
                new Scales { Id = 261, Name ="D Major", ScalesNotes = "D E F# G A B C#"},
                new Scales { Id = 262, Name ="D Minor", ScalesNotes = "D E F G A Bb C"},
                new Scales { Id = 263, Name ="D# Major", ScalesNotes = "D# E# F G# A# B# C"},
                new Scales { Id = 264, Name ="D# Minor", ScalesNotes = "D# E# F# G# A# B C#"},
                new Scales { Id = 265, Name ="E Major", ScalesNotes = "E F# G# A B C# D#"},
                new Scales { Id = 266, Name ="E Minor", ScalesNotes = "E F# G A B C D"},
                new Scales { Id = 267, Name ="F Major", ScalesNotes = "F G A Bb C D E"},
                new Scales { Id = 268, Name ="F Minor", ScalesNotes = "F G Ab Bb C Db Eb"},
                new Scales { Id = 269, Name ="F# Major", ScalesNotes = "F# G# A# B C# D# E#"},
                new Scales { Id = 270, Name ="F# Minor", ScalesNotes = "F# G# A B C# D E"},
                new Scales { Id = 271, Name ="G Major", ScalesNotes = "G A B C D E F#"},
                new Scales { Id = 272, Name ="G Minor", ScalesNotes = "G A Bb C D Eb F"},
                new Scales { Id = 273, Name ="G# Major", ScalesNotes = "G# A# B# C# D# E# F"},
                new Scales { Id = 274, Name ="G# Minor", ScalesNotes = "G# A# B C# D# E F#"},
                new Scales { Id = 275, Name ="A Major", ScalesNotes = "A B C# D E F# G#"},
                new Scales { Id = 276, Name ="A Minor", ScalesNotes = "A B C D E F G"},
                new Scales { Id = 277, Name ="A# Major", ScalesNotes = "A# B# C D# E# F G"},
                new Scales { Id = 278, Name ="A# Minor", ScalesNotes = "A# B# C# D# E# F# G#"},
                new Scales { Id = 279, Name ="B Major", ScalesNotes = "B C# D# E F# G# A#"},
                new Scales { Id = 280, Name ="B Minor", ScalesNotes = "B C# D E F# G A"},
            };

            if (scalesCount > 0)
            {
                return _database.UpdateAllAsync(scales);
            }
            else
            {
                return _database.InsertAllAsync(scales);
            }
        }

        //===========================================

        public Task<List<Tuning>> GetTuningsAsync() => _database.Table<Tuning>().ToListAsync();
        public Task<List<Scales>> GetScalesAsync() => _database.Table<Scales>().ToListAsync();
        public Task<Tuning> GetTuningWithId (int id) => _database.Table<Tuning>().Where(i => i.Id == id).FirstOrDefaultAsync();
        public Task<SoundProps> GetNoteFromName(string name) => 
            _database.Table<SoundProps>().Where(i => i.Note == name).FirstOrDefaultAsync();
        public Task<int> CountNotesAsync() => _database.Table<SoundProps>().CountAsync();
        public Task<int> CountTuningsAsync() => _database.Table<Tuning>().CountAsync();
        public Task<int> CountScalesAsync() => _database.Table<Scales>().CountAsync();
        public Task<SoundProps> GetNoteFromDbAsync(double frequency) => 
            _database.Table<SoundProps>().Where(i => (i.MinFreq <= frequency) &&  (frequency <= i.MaxFreq)).FirstOrDefaultAsync();

    }
}